# Site settings
title: Breizh Original Crêperie
email: enquire@breizhoriginal.com.au
description: "Best Crêpes and Galettes in Perth, Western Australia. Authentic French food Crêperie."
baseurl: ""
url: 0.0.0.0:4000 #"http://www.breizhoriginal.com.au"

# Build settings
markdown: kramdown
permalink: pretty
