# Site settings
title: Breizh Original Crêperie
email: breizhoriginal@gmail.com
description: "Best Crêpes and Galettes in Perth, Western Australia. Authentic French food Crêperie. Selecting wholesome, organic and best ingredients that can be found."
baseurl: ""
url: "http://0.0.0.0:4000"

# Build settings
markdown: kramdown
permalink: pretty
